import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";
import { ReactNode } from "react";
import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from "@/components/ui/theme-provider"
import { SessionProvider } from "next-auth/react"
import { auth } from "@/auth"


const SpaceGrotesk = localFont({
  src: "./fonts/SpaceGrotesk.woff",
  variable: "--font-space-grotesk",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: ReactNode }) => {
    const session = await auth()

    return (
    <html lang="en">
    <SessionProvider session={session}>
        <body
            className={`${SpaceGrotesk.className} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
        >
            {children}
            <Toaster />
        </ThemeProvider>
        </body>
    </SessionProvider>
    </html>
  );
}

export default RootLayout;
